### ISSUE TITLE
Add compression threshold

### ISSUE THREAD

**Issue by Xenira** [panzi/rust-u4pak#26]
UnrealPak does not compress files that can't get much smaller by compressing them.
This should also be supported by u4pak, as the compression block overhead inflates the file unnecessarily and extracting compressed resources takes more computation.

**TODO:**
- [ ] Figure out default threshold
- [ ] Add command line parameter for setting/disabling threshold
- [ ] Add check if file should be compressed

**Comment by panzi** [comment]
Ok, I've added an option for the threshold of files under which they shan't be compressed. See `--compression-min-size`

**Comment by Xenira** [comment]
> Also it now checks if the file didn't shrink after compression and writes the uncompressed file instead in that case. This feature needs testing.

This is actually what I wanted to do in this issue :)

**Comment by panzi** [comment]
Yeah, I felt like implementing that. :smile: Do you have any tests with files where you know they grow in size when trying to compress them?

**Comment by Xenira** [comment]
The current files should have a jpg, that is not compressed (need to add a png, to test compression with larger files when I think about it).
